"""login attempts

Revision ID: 867d060d677d
Revises: 8cfc9fb20cab
Create Date: 2026-09-26 14:08:06.361147
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import taskboard.db.base

revision: str = "867d060d677d"
down_revision: str | None = "8cfc9fb20cab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("username", sa.Unicode(length=100), nullable=False),
        sa.Column("ip_address", sa.Unicode(length=45), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_attempts_at"), ["at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_login_attempts_ip_address"), ["ip_address"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_login_attempts_username"), ["username"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_username"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_ip_address"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_at"))

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
