"""sso requests and group mappings

Revision ID: 6bbf2e3943cd
Revises: 867d060d677d
Create Date: 2026-09-26 16:12:41.117983
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import taskboard.db.base

revision: str = "6bbf2e3943cd"
down_revision: str | None = "867d060d677d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sso_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state_hash", sa.Unicode(length=64), nullable=False),
        sa.Column("provider", sa.Unicode(length=50), nullable=False),
        sa.Column("nonce", sa.Unicode(length=100), nullable=False),
        sa.Column("code_verifier", sa.Unicode(length=128), nullable=False),
        sa.Column("return_to", sa.Unicode(length=1000), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sso_requests")),
        sa.UniqueConstraint("state_hash", name=op.f("uq_sso_requests_state_hash")),
    )
    with op.batch_alter_table("sso_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sso_requests_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "group_role_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Unicode(length=50), nullable=False),
        sa.Column("group_name", sa.Unicode(length=255), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("scope_key", sa.Unicode(length=40), nullable=False),
        sa.CheckConstraint(
            "department_id IS NULL OR section_id IS NULL",
            name=op.f("ck_group_role_mappings_one_scope_only"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_group_role_mappings_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_group_role_mappings_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_group_role_mappings_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_role_mappings")),
        sa.UniqueConstraint(
            "provider",
            "group_name",
            "role_id",
            "scope_key",
            name=op.f("uq_group_role_mappings_provider_group_name_role_id_scope_key"),
        ),
    )
    with op.batch_alter_table("group_role_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_role_mappings_role_id"), ["role_id"], unique=False
        )

    with op.batch_alter_table("external_identities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("groups", sa.JSON(), nullable=False, server_default="[]"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_identities", schema=None) as batch_op:
        batch_op.drop_column("groups")

    with op.batch_alter_table("group_role_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_role_mappings_role_id"))

    op.drop_table("group_role_mappings")
    with op.batch_alter_table("sso_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sso_requests_created_at"))

    op.drop_table("sso_requests")
    # ### end Alembic commands ###
