"""processes

Revision ID: 43353ae16098
Revises: 6bbf2e3943cd
Create Date: 2026-10-04 15:24:59.067083
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "43353ae16098"
down_revision: str | None = "6bbf2e3943cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=20), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_processes_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processes")),
        sa.UniqueConstraint("code", name=op.f("uq_processes_code")),
    )
    with op.batch_alter_table("processes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_processes_section_id"), ["section_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("processes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_processes_section_id"))

    op.drop_table("processes")
    # ### end Alembic commands ###
