"""releases

Revision ID: d8d4a375aeac
Revises: a58ea5830fe1
Create Date: 2026-10-04 23:35:05.633974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import taskboard.db.base

revision: str = "d8d4a375aeac"
down_revision: str | None = "a58ea5830fe1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("note", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False),
        sa.Column("released_by_user_id", sa.Integer(), nullable=True),
        sa.Column("released_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.CheckConstraint("number >= 1", name=op.f("ck_releases_number_positive")),
        sa.ForeignKeyConstraint(
            ["process_id"], ["processes.id"], name=op.f("fk_releases_process_id_processes")
        ),
        sa.ForeignKeyConstraint(
            ["released_by_user_id"],
            ["users.id"],
            name=op.f("fk_releases_released_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
        sa.UniqueConstraint("process_id", "number", name=op.f("uq_releases_process_id_number")),
    )
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_releases_process_id"), ["process_id"], unique=False)

    op.create_table(
        "release_items",
        sa.Column("release_id", sa.Integer(), nullable=False),
        sa.Column(
            "object_type",
            sa.Enum("box", "link", "control", name="objecttype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"], ["releases.id"], name=op.f("fk_release_items_release_id_releases")
        ),
        sa.PrimaryKeyConstraint(
            "release_id", "object_type", "object_id", name=op.f("pk_release_items")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_items")
    with op.batch_alter_table("releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_releases_process_id"))

    op.drop_table("releases")
    # ### end Alembic commands ###
