"""process knowledge

Revision ID: accb969d56e3
Revises: 5337a4d5fc47
Create Date: 2026-10-04 16:12:29.527434
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import taskboard.db.base

revision: str = "accb969d56e3"
down_revision: str | None = "5337a4d5fc47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "box_kinds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Unicode(length=40), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column(
            "description", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum(
                "step",
                "knowledge",
                "reference",
                "rule",
                "failure_mode",
                "defect",
                "plain",
                name="boxrole",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("style", sa.Unicode(length=20), nullable=False),
        sa.Column("has_facts", sa.Boolean(), nullable=False),
        sa.Column("has_main_url", sa.Boolean(), nullable=False),
        sa.Column("builtin", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("field_schema", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_box_kinds")),
        sa.UniqueConstraint("key", name=op.f("uq_box_kinds_key")),
    )
    op.create_table(
        "link_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Unicode(length=40), nullable=False),
        sa.Column("forward_name", sa.Unicode(length=100), nullable=False),
        sa.Column("backward_name", sa.Unicode(length=100), nullable=False),
        sa.Column(
            "description", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False
        ),
        sa.Column(
            "role",
            sa.Enum("leads_to", "plain", name="linkrole", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("builtin", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("field_schema", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_link_types")),
        sa.UniqueConstraint("key", name=op.f("uq_link_types_key")),
    )
    op.create_table(
        "boxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Unicode(length=60), nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=300), nullable=False),
        sa.Column("body_md", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False),
        sa.Column("main_url", sa.Unicode(length=2000), nullable=True),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("step_no", sa.Unicode(length=20), nullable=True),
        sa.Column("owner_person_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_at", sa.Date(), nullable=True),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(process_id IS NOT NULL AND section_id IS NULL)"
            " OR (process_id IS NULL AND section_id IS NOT NULL)",
            name=op.f("ck_boxes_process_or_section"),
        ),
        sa.CheckConstraint(
            "process_id IS NOT NULL OR parent_id IS NULL",
            name=op.f("ck_boxes_defects_have_no_parent"),
        ),
        sa.ForeignKeyConstraint(
            ["kind_id"], ["box_kinds.id"], name=op.f("fk_boxes_kind_id_box_kinds")
        ),
        sa.ForeignKeyConstraint(
            ["owner_person_id"], ["people.id"], name=op.f("fk_boxes_owner_person_id_people")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id", "process_id"],
            ["boxes.id", "boxes.process_id"],
            name="fk_boxes_parent_same_process",
        ),
        sa.ForeignKeyConstraint(
            ["process_id"], ["processes.id"], name=op.f("fk_boxes_process_id_processes")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_boxes_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boxes")),
        sa.UniqueConstraint("id", "process_id", name=op.f("uq_boxes_id_process_id")),
        sa.UniqueConstraint("key", name=op.f("uq_boxes_key")),
    )
    with op.batch_alter_table("boxes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_boxes_kind_id"), ["kind_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_boxes_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_boxes_process_id"), ["process_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_boxes_section_id"), ["section_id"], unique=False)
        batch_op.create_index(
            "uq_boxes_one_root_per_process",
            ["process_id"],
            unique=True,
            sqlite_where=sa.text("parent_id IS NULL AND process_id IS NOT NULL"),
            mssql_where=sa.text("parent_id IS NULL AND process_id IS NOT NULL"),
        )

    op.create_table(
        "box_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_box_id", sa.Integer(), nullable=False),
        sa.Column("to_box_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("note_md", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.CheckConstraint("from_box_id <> to_box_id", name=op.f("ck_box_links_not_to_itself")),
        sa.ForeignKeyConstraint(
            ["from_box_id"], ["boxes.id"], name=op.f("fk_box_links_from_box_id_boxes")
        ),
        sa.ForeignKeyConstraint(
            ["to_box_id"], ["boxes.id"], name=op.f("fk_box_links_to_box_id_boxes")
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["link_types.id"], name=op.f("fk_box_links_type_id_link_types")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_box_links")),
        sa.UniqueConstraint(
            "from_box_id",
            "to_box_id",
            "type_id",
            name=op.f("uq_box_links_from_box_id_to_box_id_type_id"),
        ),
    )
    with op.batch_alter_table("box_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_box_links_from_box_id"), ["from_box_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_box_links_to_box_id"), ["to_box_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_box_links_type_id"), ["type_id"], unique=False)

    op.create_table(
        "controls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("box_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("prevent", "detect", name="controlkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("text", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["box_id"], ["boxes.id"], name=op.f("fk_controls_box_id_boxes")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_controls")),
    )
    with op.batch_alter_table("controls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_controls_box_id"), ["box_id"], unique=False)

    op.create_table(
        "revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "object_type",
            sa.Enum("box", "link", "control", name="objecttype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.Column("box_id", sa.Integer(), nullable=False),
        sa.Column("rev", sa.Integer(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["users.id"], name=op.f("fk_revisions_author_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revisions")),
        sa.UniqueConstraint(
            "object_type", "object_id", "rev", name=op.f("uq_revisions_object_type_object_id_rev")
        ),
    )
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_revisions_box_id"), ["box_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_revisions_object_id"), ["object_id"], unique=False)

    op.create_table(
        "box_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("change_id", sa.Integer(), nullable=True),
        sa.Column("box_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "affects", "related", "action", name="referencerole", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(task_id IS NOT NULL AND change_id IS NULL)"
            " OR (task_id IS NULL AND change_id IS NOT NULL)",
            name=op.f("ck_box_references_one_source"),
        ),
        sa.ForeignKeyConstraint(
            ["box_id"], ["boxes.id"], name=op.f("fk_box_references_box_id_boxes")
        ),
        sa.ForeignKeyConstraint(
            ["change_id"], ["changes.id"], name=op.f("fk_box_references_change_id_changes")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_box_references_created_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_box_references_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_box_references")),
    )
    with op.batch_alter_table("box_references", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_box_references_box_id"), ["box_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_box_references_change_id"), ["change_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_box_references_task_id"), ["task_id"], unique=False)
        batch_op.create_index(
            "uq_box_references_change",
            ["change_id", "box_id", "role"],
            unique=True,
            sqlite_where=sa.text("change_id IS NOT NULL"),
            mssql_where=sa.text("change_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_box_references_task",
            ["task_id", "box_id", "role"],
            unique=True,
            sqlite_where=sa.text("task_id IS NOT NULL"),
            mssql_where=sa.text("task_id IS NOT NULL"),
        )

    op.create_table(
        "external_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("box_id", sa.Integer(), nullable=True),
        sa.Column("control_id", sa.Integer(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "dashboard",
                "graph",
                "calibration",
                "document",
                "website",
                name="externallinkkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("label", sa.Unicode(length=300), nullable=False),
        sa.Column("url", sa.Unicode(length=2000), nullable=False),
        sa.Column("pass_box_param", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(box_id IS NOT NULL AND control_id IS NULL)"
            " OR (box_id IS NULL AND control_id IS NOT NULL)",
            name=op.f("ck_external_links_one_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["box_id"], ["boxes.id"], name=op.f("fk_external_links_box_id_boxes")
        ),
        sa.ForeignKeyConstraint(
            ["control_id"], ["controls.id"], name=op.f("fk_external_links_control_id_controls")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_links")),
    )
    with op.batch_alter_table("external_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_external_links_box_id"), ["box_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_external_links_control_id"), ["control_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("external_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_links_control_id"))
        batch_op.drop_index(batch_op.f("ix_external_links_box_id"))

    op.drop_table("external_links")
    with op.batch_alter_table("box_references", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_box_references_task",
            sqlite_where=sa.text("task_id IS NOT NULL"),
            mssql_where=sa.text("task_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_box_references_change",
            sqlite_where=sa.text("change_id IS NOT NULL"),
            mssql_where=sa.text("change_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_box_references_task_id"))
        batch_op.drop_index(batch_op.f("ix_box_references_change_id"))
        batch_op.drop_index(batch_op.f("ix_box_references_box_id"))

    op.drop_table("box_references")
    with op.batch_alter_table("revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_revisions_object_id"))
        batch_op.drop_index(batch_op.f("ix_revisions_box_id"))

    op.drop_table("revisions")
    with op.batch_alter_table("controls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_controls_box_id"))

    op.drop_table("controls")
    with op.batch_alter_table("box_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_box_links_type_id"))
        batch_op.drop_index(batch_op.f("ix_box_links_to_box_id"))
        batch_op.drop_index(batch_op.f("ix_box_links_from_box_id"))

    op.drop_table("box_links")
    with op.batch_alter_table("boxes", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_boxes_one_root_per_process",
            sqlite_where=sa.text("parent_id IS NULL AND process_id IS NOT NULL"),
            mssql_where=sa.text("parent_id IS NULL AND process_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_boxes_section_id"))
        batch_op.drop_index(batch_op.f("ix_boxes_process_id"))
        batch_op.drop_index(batch_op.f("ix_boxes_parent_id"))
        batch_op.drop_index(batch_op.f("ix_boxes_kind_id"))

    op.drop_table("boxes")
    op.drop_table("link_types")
    op.drop_table("box_kinds")
    # ### end Alembic commands ###
