"""initial schema

Revision ID: 8cfc9fb20cab
Revises:
Create Date: 2026-09-26 14:00:50.869432
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import taskboard.db.base

revision: str = "8cfc9fb20cab"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_locks",
        sa.Column("name", sa.Unicode(length=50), nullable=False),
        sa.Column("counter", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_app_locks")),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=20), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("code", name=op.f("uq_departments_code")),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Unicode(length=20), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("color", sa.Unicode(length=7), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("key", name=op.f("uq_projects_key")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Unicode(length=50), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column(
            "description", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False
        ),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("key", name=op.f("uq_roles_key")),
    )
    op.create_table(
        "project_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id", "project_id"],
            ["project_nodes.id", "project_nodes.project_id"],
            name="fk_project_nodes_parent_same_project",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_nodes_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_nodes")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_project_nodes_id_project_id")),
    )
    with op.batch_alter_table("project_nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_nodes_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_project_nodes_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission", sa.Unicode(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("role_id", "permission", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Unicode(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_sections_department_id_departments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("department_id", "name", name=op.f("uq_sections_department_id_name")),
    )
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sections_department_id"), ["department_id"], unique=False
        )

    op.create_table(
        "people",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Unicode(length=8), nullable=False),
        sa.Column("name", sa.Unicode(length=200), nullable=False),
        sa.Column("color", sa.Unicode(length=7), nullable=False),
        sa.Column("email", sa.Unicode(length=254), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_people_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
        sa.UniqueConstraint("code", name=op.f("uq_people_code")),
    )
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_people_section_id"), ["section_id"], unique=False)
        batch_op.create_index(
            "uq_people_email",
            ["email"],
            unique=True,
            sqlite_where=sa.text("email IS NOT NULL"),
            mssql_where=sa.text("email IS NOT NULL"),
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Unicode(length=100), nullable=False),
        sa.Column("display_name", sa.Unicode(length=200), nullable=False),
        sa.Column("email", sa.Unicode(length=254), nullable=True),
        sa.Column("person_id", sa.Integer(), nullable=True),
        sa.Column("password_hash", sa.Unicode(length=255), nullable=True),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "suspended", "pending", name="userstatus", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "kind",
            sa.Enum("regular", "anonymous", name="userkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_login_at", taskboard.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_users_person_id_people")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "uq_users_email",
            ["email"],
            unique=True,
            sqlite_where=sa.text("email IS NOT NULL"),
            mssql_where=sa.text("email IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_users_person_id",
            ["person_id"],
            unique=True,
            sqlite_where=sa.text("person_id IS NOT NULL"),
            mssql_where=sa.text("person_id IS NOT NULL"),
        )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.Unicode(length=60), nullable=False),
        sa.Column("target_type", sa.Unicode(length=40), nullable=True),
        sa.Column("target_id", sa.Unicode(length=60), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_log_actor_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_at"), ["at"], unique=False)

    op.create_table(
        "external_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.Unicode(length=50), nullable=False),
        sa.Column("subject", sa.Unicode(length=255), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", taskboard.db.base.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_external_identities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_identities")),
        sa.UniqueConstraint(
            "provider", "subject", name=op.f("uq_external_identities_provider_subject")
        ),
    )
    with op.batch_alter_table("external_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_external_identities_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "role_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("scope_key", sa.Unicode(length=40), nullable=False),
        sa.CheckConstraint(
            "department_id IS NULL OR section_id IS NULL",
            name=op.f("ck_role_assignments_one_scope_only"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_role_assignments_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_assignments_role_id_roles")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_role_assignments_section_id_sections")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_role_assignments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint(
            "user_id",
            "role_id",
            "scope_key",
            name=op.f("uq_role_assignments_user_id_role_id_scope_key"),
        ),
    )
    with op.batch_alter_table("role_assignments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_assignments_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_role_assignments_user_id"), ["user_id"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.Unicode(length=16), nullable=False),
        sa.Column("title", sa.Unicode(length=300), nullable=False),
        sa.Column(
            "description", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False
        ),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "idea",
                "started",
                "done",
                "archived",
                name="taskstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("lead_person_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("updated_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"], ["users.id"], name=op.f("fk_tasks_created_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["lead_person_id"], ["people.id"], name=op.f("fk_tasks_lead_person_id_people")
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name=op.f("fk_tasks_section_id_sections")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        sa.UniqueConstraint("key", name=op.f("uq_tasks_key")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_lead_person_id"), ["lead_person_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tasks_rank"), ["rank"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_section_id"), ["section_id"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.Unicode(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("expires_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("last_seen_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("ip_address", sa.Unicode(length=45), nullable=True),
        sa.Column("user_agent", sa.Unicode(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_sessions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "created",
                "status_changed",
                "lead_changed",
                "helper_added",
                "helper_removed",
                "section_changed",
                "placement_added",
                "placement_moved",
                "placement_removed",
                name="eventkind",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_events_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_task_id"), ["task_id"], unique=False)

    op.create_table(
        "placements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id", "project_id"],
            ["project_nodes.id", "project_nodes.project_id"],
            name="fk_placements_node_same_project",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_placements_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_placements_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placements")),
        sa.UniqueConstraint("task_id", "project_id", name=op.f("uq_placements_task_id_project_id")),
    )
    with op.batch_alter_table("placements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_placements_node_id"), ["node_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_placements_project_id"), ["project_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_placements_task_id"), ["task_id"], unique=False)

    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.Column("edited_at", taskboard.db.base.UTCDateTime(), nullable=True),
        sa.Column("body_md", sa.UnicodeText().with_variant(sa.NVARCHAR(), "mssql"), nullable=False),
        sa.Column("is_update", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["users.id"], name=op.f("fk_posts_author_user_id_users")
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], name=op.f("fk_posts_task_id_tasks")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_posts_author_user_id"), ["author_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_posts_task_id"), ["task_id"], unique=False)

    op.create_table(
        "task_helpers",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_task_helpers_person_id_people")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_task_helpers_task_id_tasks")
        ),
        sa.PrimaryKeyConstraint("task_id", "person_id", name=op.f("pk_task_helpers")),
    )
    with op.batch_alter_table("task_helpers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_helpers_person_id"), ["person_id"], unique=False)

    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Unicode(length=32), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("uploader_user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.Unicode(length=255), nullable=False),
        sa.Column("content_type", sa.Unicode(length=100), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", taskboard.db.base.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_attachments_post_id_posts")
        ),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_attachments_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["uploader_user_id"], ["users.id"], name=op.f("fk_attachments_uploader_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attachments")),
        sa.UniqueConstraint("public_id", name=op.f("uq_attachments_public_id")),
    )
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attachments_post_id"), ["post_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_attachments_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attachments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attachments_task_id"))
        batch_op.drop_index(batch_op.f("ix_attachments_post_id"))

    op.drop_table("attachments")
    with op.batch_alter_table("task_helpers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_helpers_person_id"))

    op.drop_table("task_helpers")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_task_id"))
        batch_op.drop_index(batch_op.f("ix_posts_author_user_id"))

    op.drop_table("posts")
    with op.batch_alter_table("placements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_placements_task_id"))
        batch_op.drop_index(batch_op.f("ix_placements_project_id"))
        batch_op.drop_index(batch_op.f("ix_placements_node_id"))

    op.drop_table("placements")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_task_id"))

    op.drop_table("events")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_expires_at"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_section_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_rank"))
        batch_op.drop_index(batch_op.f("ix_tasks_lead_person_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("role_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_assignments_user_id"))
        batch_op.drop_index(batch_op.f("ix_role_assignments_role_id"))

    op.drop_table("role_assignments")
    with op.batch_alter_table("external_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_external_identities_user_id"))

    op.drop_table("external_identities")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_at"))

    op.drop_table("audit_log")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_users_person_id",
            sqlite_where=sa.text("person_id IS NOT NULL"),
            mssql_where=sa.text("person_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_users_email",
            sqlite_where=sa.text("email IS NOT NULL"),
            mssql_where=sa.text("email IS NOT NULL"),
        )

    op.drop_table("users")
    with op.batch_alter_table("people", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_people_email",
            sqlite_where=sa.text("email IS NOT NULL"),
            mssql_where=sa.text("email IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_people_section_id"))

    op.drop_table("people")
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sections_department_id"))

    op.drop_table("sections")
    op.drop_table("role_permissions")
    with op.batch_alter_table("project_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_nodes_project_id"))
        batch_op.drop_index(batch_op.f("ix_project_nodes_parent_id"))

    op.drop_table("project_nodes")
    op.drop_table("roles")
    op.drop_table("projects")
    op.drop_table("departments")
    op.drop_table("app_locks")
    # ### end Alembic commands ###
