"""Generate docs/CODEMAP.md: a tree of the codebase with a one-line summary per file.

Summaries come from the code itself: the first line of each Python module docstring, and the
first comment in JS/CSS/HTML files. So the map stays correct as long as those stay correct.

    uv run python scripts/gen_codemap.py          # rewrite docs/CODEMAP.md
    uv run python scripts/gen_codemap.py --check  # exit 1 if it is stale (used by the tests)
"""

import argparse
import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "CODEMAP.md"

# What the map covers, in this order.
ENTRIES = ["app.py", "taskboard", "tests", "scripts"]
SKIP_DIRS = {"__pycache__", "vendor", "fonts", ".pytest_cache", "node_modules"}
SUMMARY_SUFFIXES = {".py", ".js", ".mjs", ".css", ".html"}
COLUMN = 44

HEADER = """\
# Code map

Generated by `scripts/gen_codemap.py` from module docstrings and file header comments.
**Do not edit by hand**: run `uv run python scripts/gen_codemap.py` after adding, moving or
re-describing files (a test fails when this file is stale).

Where to look first:

- A behaviour rule (ranking, numbering, lifecycle, keys): `taskboard/domain/`.
- Who may do what: `taskboard/identity/` (policy, permissions, roles).
- A use case (create task, move task, ...): `taskboard/services/`.
- An endpoint: `taskboard/api/routers/`, request/response shapes in `taskboard/schemas/`.
- Tables: `taskboard/db/models/`; schema changes also need an Alembic migration.
- The browser app: `taskboard/static/js/` (`views/` per screen, `components/` shared UI,
  `lib/` pure logic with unit tests in `tests/js/`).

"""

_COMMENT_PATTERNS = [
    re.compile(r"^\s*/\*\*?\s*(.+?)\s*(?:\*/)?$"),  # /** Summary   or   /* Summary */
    re.compile(r"^\s*//\s*(.+)$"),  # // Summary
    re.compile(r"^\s*<!--\s*(.+?)\s*(?:-->)?$"),  # <!-- Summary -->
]


def summarize(path: Path) -> str:
    """One-line description of a file, or '' when it has none."""
    if path.suffix == ".py":
        docstring = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
        return docstring.strip().splitlines()[0] if docstring else ""
    if path.suffix in SUMMARY_SUFFIXES:
        for line in path.read_text(encoding="utf-8").splitlines()[:5]:
            for pattern in _COMMENT_PATTERNS:
                if match := pattern.match(line):
                    return match.group(1).strip()
    return ""


def _is_listed(path: Path) -> bool:
    if path.is_dir():
        return path.name not in SKIP_DIRS and not path.name.startswith(".")
    return path.suffix in SUMMARY_SUFFIXES or path.suffix in {".md", ".json", ".ini", ".mako"}


def _dir_summary(path: Path) -> str:
    init = path / "__init__.py"
    return summarize(init) if init.exists() else ""


def _line(label: str, summary: str, depth: int) -> str:
    text = "  " * depth + label
    if not summary:
        return text
    return f"{text.ljust(COLUMN - 1)} {summary}" if len(text) < COLUMN - 1 else f"{text}  {summary}"


def _walk(path: Path, depth: int, out: list[str]) -> None:
    if path.is_dir():
        out.append(_line(f"{path.name}/", _dir_summary(path), depth))
        children = sorted(
            (c for c in path.iterdir() if _is_listed(c)), key=lambda c: (c.is_file(), c.name)
        )
        for child in children:
            if child.name == "__init__.py":
                continue  # its docstring already describes the directory
            _walk(child, depth + 1, out)
    else:
        out.append(_line(path.name, summarize(path), depth))


def render() -> str:
    lines: list[str] = []
    for entry in ENTRIES:
        path = ROOT / entry
        if path.exists():
            _walk(path, 0, lines)
    return HEADER + "```text\n" + "\n".join(lines) + "\n```\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if docs/CODEMAP.md is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current.replace("\r\n", "\n") != content:
            print("docs/CODEMAP.md is stale: run `uv run python scripts/gen_codemap.py`")
            return 1
        return 0
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
